version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          sudo pip install pipenv 
          pipenv install 
          sudo apt install python-pytest
      - run:
          command: pipenv run pytest 
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
